import React from 'react';
import HighlightedText from './HighlightedText';

export default {
  title: 'Components/HighlightedText',
  component: HighlightedText,
  tags: ['autodocs'], // Auto generate documentation
};

// Sample data for testing
const sampleSentences = [
  {
    sentence: "This is a human-written sentence.",
    result: {
      classification: "Human-Written",
      confidence: 0.92
    }
  },
  {
    sentence: "This appears to be generated by AI.",
    result: {
      classification: "AI-Generated",
      confidence: 0.87
    }
  },
  {
    sentence: "Another human written example here.",
    result: {
      classification: "Human-Written",
      confidence: 0.95
    }
  }
];

// Story with sentence analysis and legend
export const WithAnalysis = {
  args: {
    sentences: sampleSentences,
    showLegend: true
  },
};

// Story with just plain text (no analysis)
export const PlainText = {
  args: {
    text: "This is just plain text without any sentence analysis data.",
    showLegend: false
  },
};

// Story with empty data
export const Empty = {
  args: {
    text: "",
    sentences: [],
    showLegend: true
  },
};